version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: smeflow-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: smeflow
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - smeflow-network

  redis:
    image: redis:7-alpine
    container_name: smeflow-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - smeflow-network

  backend:
    build: .
    container_name: smeflow-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/smeflow?authSource=admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./logs:/app/logs
    networks:
      - smeflow-network
    command: sh -c "npm run seed && npm start"

volumes:
  mongodb_data:
  redis_data:

networks:
  smeflow-network:
    driver: bridge
